name: cat_dog_encyclopedia
description: A new Flutter application.


dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.8.0
  firebase_database : ^0.4.1
  firebase_storage : ^1.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dots_indicator: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

  # mainlogo
    - assets/images/catlogo.jpg
    - assets/images/doglogo.jpg
    - assets/images/background.jpg


  # dogs
    - assets/images/dogs/Affenpinscher.jpg
    - assets/images/dogs/Afghan_Hound.jpg
    - assets/images/dogs/Airedale_Terrier.jpg
    - assets/images/dogs/Akita.jpg
    - assets/images/dogs/Alaskan_Malamute.jpg
    - assets/images/dogs/American_English_Coonhound.jpg


  # cats
    - assets/images/cats/Abyssinian.jpg
    - assets/images/cats/American_Bobtail.jpg
    - assets/images/cats/American_Curl.jpg
    - assets/images/cats/American_Shorthair.jpg
    - assets/images/cats/American_Wirehair.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: WorkSansSemiBold
        fonts:
          - asset: assets/fonts/Work_Sans/WorkSans-Semibold.ttf

      - family: WorkSansBold
        fonts:
          - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

      - family: WorkSansMedium
        fonts:
          - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

      - family: MaliMedium
        fonts:
          - asset: assets/fonts/Mali/Mali-Medium.ttf

      - family: MaliSemiBold
        fonts:
          - asset: assets/fonts/Mali/Mali-Semibold.ttf

      - family: MaliBold
        fonts:
          - asset: assets/fonts/Mali/Mali-Bold.ttf

      - family: MaliLight
        fonts:
          - asset: assets/fonts/Mali/Mali-Light.ttf



  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
